/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardRouteRouteImport } from './routes/_onboard/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnboardRoleRouteImport } from './routes/_onboard/role'
import { Route as OnboardOnboardRouteImport } from './routes/_onboard/onboard'
import { Route as DashboardDashboardRouteImport } from './routes/_dashboard/dashboard'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as DashboardDashboardRoleRouteImport } from './routes/_dashboard/dashboard.$role'

const OnboardRouteRoute = OnboardRouteRouteImport.update({
  id: '/_onboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardRoleRoute = OnboardRoleRouteImport.update({
  id: '/role',
  path: '/role',
  getParentRoute: () => OnboardRouteRoute,
} as any)
const OnboardOnboardRoute = OnboardOnboardRouteImport.update({
  id: '/onboard',
  path: '/onboard',
  getParentRoute: () => OnboardRouteRoute,
} as any)
const DashboardDashboardRoute = DashboardDashboardRouteImport.update({
  id: '/_dashboard/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const DashboardDashboardRoleRoute = DashboardDashboardRoleRouteImport.update({
  id: '/$role',
  path: '/$role',
  getParentRoute: () => DashboardDashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof AuthLoginRoute
  '/dashboard': typeof DashboardDashboardRouteWithChildren
  '/onboard': typeof OnboardOnboardRoute
  '/role': typeof OnboardRoleRoute
  '/dashboard/$role': typeof DashboardDashboardRoleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof AuthLoginRoute
  '/dashboard': typeof DashboardDashboardRouteWithChildren
  '/onboard': typeof OnboardOnboardRoute
  '/role': typeof OnboardRoleRoute
  '/dashboard/$role': typeof DashboardDashboardRoleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_onboard': typeof OnboardRouteRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_dashboard/dashboard': typeof DashboardDashboardRouteWithChildren
  '/_onboard/onboard': typeof OnboardOnboardRoute
  '/_onboard/role': typeof OnboardRoleRoute
  '/_dashboard/dashboard/$role': typeof DashboardDashboardRoleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/onboard'
    | '/role'
    | '/dashboard/$role'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/dashboard' | '/onboard' | '/role' | '/dashboard/$role'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_onboard'
    | '/_auth/login'
    | '/_dashboard/dashboard'
    | '/_onboard/onboard'
    | '/_onboard/role'
    | '/_dashboard/dashboard/$role'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  OnboardRouteRoute: typeof OnboardRouteRouteWithChildren
  DashboardDashboardRoute: typeof DashboardDashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_onboard': {
      id: '/_onboard'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof OnboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_onboard/role': {
      id: '/_onboard/role'
      path: '/role'
      fullPath: '/role'
      preLoaderRoute: typeof OnboardRoleRouteImport
      parentRoute: typeof OnboardRouteRoute
    }
    '/_onboard/onboard': {
      id: '/_onboard/onboard'
      path: '/onboard'
      fullPath: '/onboard'
      preLoaderRoute: typeof OnboardOnboardRouteImport
      parentRoute: typeof OnboardRouteRoute
    }
    '/_dashboard/dashboard': {
      id: '/_dashboard/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_dashboard/dashboard/$role': {
      id: '/_dashboard/dashboard/$role'
      path: '/$role'
      fullPath: '/dashboard/$role'
      preLoaderRoute: typeof DashboardDashboardRoleRouteImport
      parentRoute: typeof DashboardDashboardRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface OnboardRouteRouteChildren {
  OnboardOnboardRoute: typeof OnboardOnboardRoute
  OnboardRoleRoute: typeof OnboardRoleRoute
}

const OnboardRouteRouteChildren: OnboardRouteRouteChildren = {
  OnboardOnboardRoute: OnboardOnboardRoute,
  OnboardRoleRoute: OnboardRoleRoute,
}

const OnboardRouteRouteWithChildren = OnboardRouteRoute._addFileChildren(
  OnboardRouteRouteChildren,
)

interface DashboardDashboardRouteChildren {
  DashboardDashboardRoleRoute: typeof DashboardDashboardRoleRoute
}

const DashboardDashboardRouteChildren: DashboardDashboardRouteChildren = {
  DashboardDashboardRoleRoute: DashboardDashboardRoleRoute,
}

const DashboardDashboardRouteWithChildren =
  DashboardDashboardRoute._addFileChildren(DashboardDashboardRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  OnboardRouteRoute: OnboardRouteRouteWithChildren,
  DashboardDashboardRoute: DashboardDashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
